# Generated by Django 5.1.1 on 2025-07-10 17:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collaboration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Collaboration notes"
                    ),
                ),
                ("block_hash", models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(db_index=True, max_length=255)),
                (
                    "contact_details",
                    models.CharField(default="Not provided", max_length=255),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=50,
                    ),
                ),
                ("specialization", models.CharField(default="General", max_length=255)),
                (
                    "farm_size",
                    models.FloatField(
                        default=1.0,
                        help_text="Size of the farm in acres",
                        validators=[django.core.validators.MinValueValidator(0.1)],
                    ),
                ),
                (
                    "farm_type",
                    models.CharField(
                        choices=[
                            ("arable", "Arable"),
                            ("pasture", "Pasture"),
                            ("mixed", "Mixed"),
                        ],
                        default="arable",
                        max_length=50,
                    ),
                ),
                (
                    "equipment",
                    models.TextField(
                        blank=True,
                        default="Not specified",
                        help_text="List of equipment available",
                    ),
                ),
                (
                    "certifications",
                    models.TextField(
                        blank=True,
                        default="None",
                        help_text="List of certifications and licenses",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("can_approve_activity", "Can approve farming activity")
                ],
            },
        ),
        migrations.CreateModel(
            name="Tier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "benefits",
                    models.TextField(
                        blank=True, default="", help_text="Benefits of this tier"
                    ),
                ),
                (
                    "requirements",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Requirements to achieve this tier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                (
                    "size",
                    models.FloatField(
                        help_text="Size of the farm in acres",
                        validators=[django.core.validators.MinValueValidator(0.1)],
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to="farming.farmer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollaborationFarmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(blank=True, default="", max_length=255)),
                (
                    "collaboration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farming.collaboration",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farming.farmer"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="collaboration",
            name="collaborating_farmers",
            field=models.ManyToManyField(
                through="farming.CollaborationFarmer", to="farming.farmer"
            ),
        ),
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "contact_info",
                    models.CharField(
                        blank=True, default="Not provided", max_length=255
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("farm_produce", "Farm Produce"),
                            ("agritourism", "Agritourism"),
                            ("farm_supplies", "Farm Supplies"),
                            ("services", "Services"),
                        ],
                        db_index=True,
                        default="farm_produce",
                        max_length=50,
                    ),
                ),
                (
                    "products_services",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Details of the products or services offered",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="business_images/"
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farming.farmer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FarmingActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("practice", models.CharField(db_index=True, max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("planting", "Planting"),
                            ("harvesting", "Harvesting"),
                            ("livestock_management", "Livestock Management"),
                            ("soil_preparation", "Soil Preparation"),
                        ],
                        db_index=True,
                        default="planting",
                        max_length=50,
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, default="", help_text="Details of the activity"
                    ),
                ),
                (
                    "input_quantity",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="E.g., Seeds or fertilizers used",
                        max_length=255,
                    ),
                ),
                (
                    "output_quantity",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="E.g., Crop yield",
                        max_length=255,
                    ),
                ),
                (
                    "weather_conditions",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Weather during the activity",
                        max_length=255,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="activity_images/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="activity_videos/"
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("block_hash", models.CharField(blank=True, max_length=64)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farming.farmer"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="collaboration",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="farming.farmingactivity",
            ),
        ),
        migrations.CreateModel(
            name="Incentive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.PositiveIntegerField(default=0)),
                ("redeemed", models.BooleanField(default=False)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farming.farmer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("availability", models.BooleanField(default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="farming.business",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="farming.business",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="farmer",
            name="tier",
            field=models.ForeignKey(
                blank=True,
                help_text="Tier of the farmer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="farming.tier",
            ),
        ),
    ]
